<?php
defined('ABSPATH') || exit;
function trendza_setup(): void { load_theme_textdomain('trendza', get_template_directory().'/languages'); add_theme_support('title-tag'); add_theme_support('post-thumbnails'); add_theme_support('custom-logo',['height'=>80,'width'=>240,'flex-height'=>true,'flex-width'=>true]); add_theme_support('html5',['search-form','comment-form','comment-list','gallery','caption','style','script']); add_theme_support('responsive-embeds'); add_theme_support('woocommerce'); add_theme_support('wc-product-gallery-zoom'); add_theme_support('wc-product-gallery-lightbox'); add_theme_support('wc-product-gallery-slider'); register_nav_menus(['primary'=>__('Primary Menu','trendza'),'footer'=>__('Footer Menu','trendza')]); }
add_action('after_setup_theme','trendza_setup');
function trendza_assets(): void { $v=wp_get_theme()->get('Version'); wp_enqueue_style('trendza-style',get_stylesheet_uri(),[],$v); wp_enqueue_script('trendza-theme',get_template_directory_uri().'/assets/js/theme.js',[],$v,true); }
add_action('wp_enqueue_scripts','trendza_assets');
function trendza_body_classes(array $classes): array { $classes[]='trendza-theme'; if(class_exists('WooCommerce')){$classes[]='trendza-woocommerce';} return $classes; }
add_filter('body_class','trendza_body_classes');
function trendza_get_product_trend(int $product_id): ?array { $score=get_post_meta($product_id,'_trendza_trend_score',true); $status=get_post_meta($product_id,'_trendza_trend_status',true); if($score===''||$status===''){return null;} return ['score'=>(float)$score,'status'=>sanitize_key((string)$status)]; }
function trendza_render_product_card(int $product_id): void { if(!function_exists('wc_get_product'))return; $product=wc_get_product($product_id); if(!$product)return; $trend=trendza_get_product_trend($product_id); ?><article class="product-card"><?php if($trend): ?><span class="trend-badge"><?php echo esc_html(ucfirst($trend['status'])); ?> · <?php echo esc_html(number_format_i18n($trend['score'],0)); ?></span><?php endif; ?><?php if($product->is_on_sale()): ?><span class="sale-badge">Sale</span><?php endif; ?><a class="product-image" href="<?php echo esc_url($product->get_permalink()); ?>"><?php echo wp_kses_post($product->get_image('woocommerce_thumbnail')); ?></a><div class="product-body"><div class="product-rating"><?php echo wp_kses_post(wc_get_rating_html($product->get_average_rating(),$product->get_rating_count())); ?></div><a class="product-title" href="<?php echo esc_url($product->get_permalink()); ?>"><?php echo esc_html($product->get_name()); ?></a><div class="product-price"><?php echo wp_kses_post($product->get_price_html()); ?></div></div></article><?php }
function trendza_fallback_menu(): void { echo '<ul class="main-menu"><li><a href="'.esc_url(home_url('/')).'">Home</a></li>'; if(class_exists('WooCommerce')){echo '<li><a href="'.esc_url(wc_get_page_permalink('shop')).'">Shop</a></li><li><a href="'.esc_url(wc_get_cart_url()).'">Cart</a></li>';} echo '</ul>'; }
